# Minimal ALIGNN hyperparameters for matbench_jdft2d.
model:
  name: alignn
  hidden_dim: 256
  num_layers: 6
  dropout: 0.1
  max_atomic_num: 100
  edge_dim: ${data.graph.num_rbf}
  angle_dim: ${data.graph.num_abf}
  target_norm: true
  target_norm_meta: ${data.dataset.root}/jdft2d_meta.csv
  optimizer:
    name: AdamW
    lr: 1e-3
    weight_decay: 1e-5
  scheduler:
    name: cosine
    t_max: ${trainer.trainer.max_epochs}
    eta_min: 1e-5
